name: webrtsp-signaling-server
base: core24
summary: Server for WebRTSP messaging between clients
adopt-info: server
description: |
  Enables remote access to WebRTSP agents located behind NAT.

  **Config file location:** /var/snap/webrtsp-signaling-server/common/signaling-server.conf
license: GPL-3.0
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

parts:
  coturn:
    plugin: autotools
    source: https://github.com/coturn/coturn.git
    source-branch: 4.17.2
    build-environment:
      - TURN_NO_SYSTEMD: "yes"
      - TURN_NO_MYSQL: "yes"
      - TURN_NO_PQ: "yes"
      - TURN_NO_MYSQL: "yes"
      - TURN_NO_MONGO: "yes"
      - TURN_NO_HIREDIS: "yes"
      - TURN_NO_PROMETHEUS: "yes"
    autotools-configure-parameters:
      - --prefix=/opt/coturn
      - --turndb=/var/snap/${SNAPCRAFT_PROJECT_NAME}/common
    build-packages:
      - libevent-dev
      - libsqlite3-dev
    stage-packages:
      - libevent-2.1-7
      - libevent-core-2.1-7
      - libevent-extra-2.1-7
      - libevent-openssl-2.1-7
      - libevent-pthreads-2.1-7
  coturn.sh:
    plugin: dump
    source: .
    organize:
        coturn.sh: opt/coturn/bin/
    stage:
        - opt/coturn/bin/coturn.sh
  server:
    plugin: cmake
    source-type: git
    source: .
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME}
    override-pull: |
        craftctl default
        craftctl set version="$(git describe --always)"
    build-snaps:
      - node/24/stable
    build-packages:
      - g++
      - ninja-build
      - libglib2.0-dev
      - libspdlog-dev
      - libconfig-dev
      - libwebsockets-dev
      - libnice-dev
      - libmicrohttpd-dev
    stage-packages:
      - libconfig9
      - libspdlog1.12
      - libwebsockets19t64
      - libwebsockets-evlib-glib
      - libnice10
      - libmicrohttpd12
      - pwgen
apps:
  SignalingServer:
    command: opt/${SNAPCRAFT_PROJECT_NAME}/bin/SignalingServer
    daemon: simple
    plugs:
      - network-bind
      - network
    restart-delay: 3s
    environment:
      PATH: $SNAP/opt/coturn/bin:${PATH}
  Coturn:
    command: opt/coturn/bin/coturn.sh
    daemon: simple
    plugs:
      - network-bind
      - network
    install-mode: disable
    restart-delay: 3s
    after:
      - SignalingServer
