#!/bin/sh -e

umask 027

cp "${SNAP}/opt/coturn/etc/turnserver.conf.default" "${SNAP_COMMON}/turnserver.conf"
cp "${SNAP}/opt/${SNAP_NAME}/etc/signaling-server.conf.sample" "${SNAP_COMMON}/signaling-server.conf"
